### ISSUE TITLE
Getting desktop for cubietruck

### ISSUE THREAD

**Issue by JazzzzX** [IGNNE/cubietruck-armbian-unofficial#1]
Hi ,
I have seen this build from the armbian forum, I was trying to use my old cubietruck, I havent found a image with a desktop environment, Do you have any images? I have tried this 
https://github.com/armbian/community/releases/download/202242/Armbian_22.11.0-trunk_Cubietruck_jammy_current_5.15.73_xfce_desktop.img.xz#cubietruck

But only the boot logs are showing in the monitor,, when initialising desktop it just shows a black screen, Do you have any image with a Desktop gui on the cubietruck? It will be very helpfull.

Thank you

**Comment by IGNNE** [comment]
Hi, and sorry for the late answer. I just built the image from the exact same sources as Armbian does, and enabled a few debug options (mostly powersave things). I haven't tried to run a desktop, but I remember that it "just worked", mostly with HDMI. You could maybe try ArchLinuxARM, and see if this is an armbian-specific issue or a kernel one..

**Comment by IGNNE** [comment]
Someone fixed it, yay! See https://github.com/IGNNE/cubietruck-armbian-unofficial/releases/tag/22.04-2023-01-11 for more info.
